filter:
    paths: ["src/*"]
    excluded_paths: ["vendor/*", "tests/*"]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: false

build:
    environment:
        php: 7.4
        mysql: true
        node: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
    services:
        mysql: 5.7
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
        before:
            - composer self-update
            - composer update --no-interaction --prefer-dist --no-progress
            - mysql -uroot -e 'CREATE DATABASE phinx_test'
    tests:
        before:
            -
                command: composer test:coverage
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
